version: "3.8"

services:
  fastapi_server:
    container_name: fastapi_server
    build: ./backend
    restart: always
    command: "sh -c 'uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 9090'"
    volumes:
      - ./backend:/code
    expose:
      - 9090
    ports:
      - "9090:9090"
    env_file: ".env"
