PATH_RAW_PDF: "data/raw"
PATH_EXTRACTION: "data/extraction"
COLLECTION_NAME: "docs"

PDF_PARSER: "PyMuPDF"
EMBEDDING_MODEL: "text-embedding-ada-002"
TOKENIZER_CHUNK_SIZE: 2000
TOKENIZER_CHUNK_OVERLAP: 200
